import crafttweaker.api.BracketHandlers;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.util.text.MCTextComponent;
import crafttweaker.api.util.text.MCStyle;

// mods.recipestages.Recipes.setRecipeStageByMod("lost_knowledge_factory_follies", "silents_mechanisms");

// mods.recipestages.Recipes.clearRecipeStage(<item:minecraft:stone_hoe>);

mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:tin_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:silver_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lead_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:nickel_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:platinum_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:zinc_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:copper_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bauxite_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:uranium_ore>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:redstone_alloy_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:copper_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:tin_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:silver_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lead_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:nickel_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:platinum_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:zinc_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:uranium_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bronze_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:brass_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:invar_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:electrum_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:steel_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_brass_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_steel_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_steel_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:signalum_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lumium_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:enderium_block>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:redstone_alloy_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:redstone_alloy_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:redstone_alloy_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:refined_iron_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:compressed_iron_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:iron_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:gold_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:copper_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:copper_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:copper_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:tin_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:tin_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:tin_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:silver_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:silver_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:silver_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lead_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lead_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lead_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:nickel_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:nickel_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:nickel_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:platinum_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:platinum_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:platinum_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:zinc_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:zinc_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:zinc_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:uranium_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:uranium_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:uranium_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bronze_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bronze_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bronze_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:brass_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:brass_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:brass_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:invar_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:invar_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:invar_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:electrum_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:electrum_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:electrum_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:steel_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:steel_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:steel_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_brass_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_brass_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_brass_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_steel_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_steel_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:aluminum_steel_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_steel_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_steel_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:bismuth_steel_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:signalum_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:signalum_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:signalum_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lumium_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lumium_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:lumium_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:enderium_dust>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:enderium_ingot>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:enderium_nugget>);
mods.recipestages.Recipes.clearRecipeStage(<item:silents_mechanisms:coal_dust>);

<item:silents_mechanisms:wrench>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:oak_drying_rack>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:empty_canister>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:coal_generator>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:battery>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:wire>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:refinery>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:solidifier>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:crusher>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:alloy_smelter>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:diesel_generator>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:battery_box>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:compressor>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:basic_alloy_smelter>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:basic_crusher>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:hand_pump>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:mixer>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:pump>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:electric_furnace>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:lava_generator>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:output_chance_upgrade>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:range_upgrade>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:processing_speed_upgrade>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:energy_efficiency_upgrade>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:infuser>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:dark_oak_drying_rack>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:acacia_drying_rack>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:jungle_drying_rack>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:spruce_drying_rack>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:alloy_machine_frame>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:stone_machine_frame>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:plastic_sheet>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:plastic_pellets>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:solder>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:heating_element>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:circuit_board>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:upgrade_case>.addTooltip("Lost Knowledge - Factory Follies");
<item:silents_mechanisms:birch_drying_rack>.addTooltip("Lost Knowledge - Factory Follies");


mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:wrench>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:oak_drying_rack>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:empty_canister>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:coal_generator>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:battery>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:wire>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:refinery>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:solidifier>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:crusher>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:alloy_smelter>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:diesel_generator>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:battery_box>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:compressor>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:basic_alloy_smelter>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:basic_crusher>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:hand_pump>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:mixer>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:pump>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:electric_furnace>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:lava_generator>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:output_chance_upgrade>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:range_upgrade>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:processing_speed_upgrade>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:energy_efficiency_upgrade>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:infuser>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:dark_oak_drying_rack>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:acacia_drying_rack>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:jungle_drying_rack>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:spruce_drying_rack>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:alloy_machine_frame>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:stone_machine_frame>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:plastic_sheet>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:plastic_pellets>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:solder>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:heating_element>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:circuit_board>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:upgrade_case>);
mods.recipestages.Recipes.setRecipeStage("lost_knowledge_factory_follies", <item:silents_mechanisms:birch_drying_rack>);