
[General]
	#Specifies rules for accepting or rejecting biomes.
	Dragourd_Spawn_Biomes = ["minecraft:dark_forest", "minecraft:dark_forest_hills"]
	#Should Dragourds spawn everywhere on full moons?
	Dragourds_Spawn_Everywhere = true

