
[enhancers]
	#The mineral concentration percentage increase that a Calvinite
	#Enhancer block gives the Mineral Soil block it's placed under.
	#(type=double, min=1.0, max=40.0, default=10.0)
	calvinite-mineral-concentration-increase = 10.0
	#The mineral concentration percentage increase that a Sylvanite
	#Enhancer block gives the Mineral Soil block it's placed under.
	#(type=double, min=2.0, max=50.0, default=25.0)
	sylvanite-mineral-concentration-increase = 25.0

[mineral-stone]
	#The amount of extra Mineral Rocks Mineral Stone will give
	#when mined (based on [chance-of-extra-drops]).
	#(type=integer, min=0, max=64, default=2)
	number-of-extra-drops = 2
	#The chance of Mineral Stone giving extra Mineral Rocks when mined (0% to 100%).
	#(type=double, min=0.0, max=100.0, default=20.0)
	chance-of-extra-drops = 20.0
	#The minimum number of experience orbs Mineral Stone will drop when mined.
	#(type=integer, min=0, max=100, default=3)
	minimum-experience-dropped = 3
	#The minimum number of Mineral Rocks dropped by Mineral Stone when it's mined.
	#(type=integer, min=0, max=64, default=1)
	number-of-base-drops = 1
	#The maximum number of experience orbs Mineral Stone will drop when mined.
	#(type=integer, min=0, max=100, default=7)
	maximum-experience-dropped = 7

[mineral-crystal]
	#Enable this (set to true) to allow turning dirt or grass into
	#Mineral Soil directly by using the item on the dirt or grass block
	#without having to use the Mineral Hoe. Use this mode when the Mineral
	#Hoe is broken or cannot be used.
	#(type=boolean, default=false)
	enable-emergency-conversion-mode = false

[mineral-hoe]
	#When enabled, the Mineral Hoe will spawn flame particles whenever
	#tilling a block.
	#(type=boolean, default=true)
	show-particles = true
	#The maximum amount of charges a single Mineral Hoe can store.
	#(type=integer, min=1, max=640, default=64)
	maximum-number-of-charges = 64
	#The amount of charges a Mineral Hoe will have when first crafted.
	#(type=integer, min=0, max=2, default=2)
	number-of-initial-charges = 2
	#When enabled, the Mineral Hoe will play a sound when trying to
	#till a block without enough charges.
	#(type=boolean, default=true)
	play-failure-sound = true
	#When enabled, the Mineral Hoe will play a sound whenever a charge (Mineral
	#Crystal) is added to it.
	#(type=boolean, default=true)
	play-charge-sound = true
	#Set to false to prevent the Mineral Hoe from being used
	#to turn dirt or grass into Mineral Enriched Soil.
	#(type=boolean, default=true)
	enable-mineral-hoe = true

[mystical-seed-pod]
	#Allows enabling or disabling the generating of Mystical Seed Pods in the world.
	#Set this to false to prevent Mystical Seed Pods from generating in the world.
	#(type=boolean, default=true)
	generate-in-world = true
	#The frequency (or the number of times) that Mystical Seed Pods will generate in the world.
	#Setting this to a higher value will generate more Mystical Seed Pods
	#(type=integer, min=1, max=70, default=5)
	frequency-of-generation = 5
	#Set to true to make the Mystical Seed Pod drop a random Biochemical (mob drop)
	#seed when broken. This can be useful for players playing on peaceful mode who can
	#otherwise not get mob drops
	#(type=boolean, default=false)
	enable-drops-from-seed-pod = false

[general-resynth-config]
	#The maximum amount of characters allowed on a single line in an item or block tooltip.
	#(type=integer, min=20, max=70, default=40)
	tooltip-character-limit = 40
	#Allows turning on or off light penalties in plant growth.
	#When set to 'true', plants will grow slightly slower with less light.
	#(type=boolean, default=true)
	enable-light-penalty = true
	#Enables features related to debugging and development.
	#It's unlikely you'd want to enable this.
	#(type=boolean, default=false)
	enable-debug-help = false
	#Allows auto-farming using hoppers when true, where plants will drop their produce in a hopper underneath the plant when fully grown, starting the growth cycle over.
	#(type=boolean, default=true)
	allow-hopper-auto-farming = true
	#Set to true to show detailed and descriptive tooltips on all Resynth blocks & items.
	#(type=boolean, default=true)
	enable-descriptive-tooltips = true
	#Enables or disables all the analytical features of the mod.
	#Including usage and error reports (all sent reports are anonymous).
	#False to disable, true to enable.
	#(type=boolean, default=true)
	enable-analytics = true

[mineral-soil]
	#The Mineral Content a single Mineral Rock is worth. WARNING: Setting this value to one that
	#does not eventually add up to 50 (taking into account the starting mineral content), will
	#cause Mineral Rocks to be lost when breaking Mineral Soil blocks with a high/full Mineral
	#Content.
	#(type=double, min=0.1, max=50.0, default=1.0)
	mineral-rock-worth = 1.0
	#When enabled, a chat message containing the Mineral Content of
	#the Mineral Soil block will be displayed, when adding Mineral Rocks
	#to the block
	#(type=boolean, default=false)
	enable-chat-message = false
	#The initial/starting Mineral Content of every Mineral Soil block when it's
	#first placed/created.
	#(type=double, min=0.1, max=50.0, default=1.0)
	initial-mineral-content = 1.0

